apiVersion: v1
kind: Service
metadata:
  name: jokes-service

spec:
  selector:
    app: jokes
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080   # port of the pods
  type: LoadBalancer # LoadBalancer - layer 3 as network load balancer, Ingress layer 7